#!/usr/bin/env python3
"""
Setup script for docpull UI.

Prompts for the API URL and saves it to config.py.
"""

from pathlib import Path


def setup():
    print("=" * 70)
    print("Docpull UI Setup")
    print("=" * 70)
    print()
    print("STEP 1: Start the API (if not already running)")
    print("-" * 70)
    print("In another terminal window, run:")
    print("  modal serve content-scraper-api.py")
    print()
    print("Wait for it to start, then look for a URL like:")
    print("  \u2713 Created web function fastapi_app")
    print("    => https://yourname--content-scraper-api-fastapi-app-dev.modal.run")
    print()
    print("STEP 2: Enter the API URL")
    print("-" * 70)

    api_url = input("Paste your API URL here: ").strip()

    if not api_url:
        print()
        print("\u2717 Error: API URL cannot be empty")
        print("Please run the setup again when you have the API URL.")
        return

    if not api_url.startswith("https://"):
        print()
        print("\u26A0 Warning: API URL should start with https://")
        print(f"You entered: {api_url}")
        confirm = input("Continue anyway? (y/n): ").strip().lower()
        if confirm != "y":
            print("Setup cancelled.")
            return

    # Validate URL format
    if "modal.run" not in api_url and "localhost" not in api_url:
        print()
        print("\u26A0 Warning: URL doesn't look like a Modal or localhost URL")
        print(f"You entered: {api_url}")
        confirm = input("Continue anyway? (y/n): ").strip().lower()
        if confirm != "y":
            print("Setup cancelled.")
            return

    # Write config file
    config_path = Path(__file__).parent / "config.py"
    config_content = f'''"""
UI Configuration - Auto-generated by setup.py
"""

SCRAPER_API_URL = "{api_url}"
IS_PROD = False
'''

    config_path.write_text(config_content)

    print()
    print("=" * 70)
    print("\u2713 Setup Complete!")
    print("=" * 70)
    print()
    print(f"API URL configured: {api_url}")
    print(f"Config saved to: {config_path}")
    print()
    print("STEP 3: Start the UI")
    print("-" * 70)
    print("Run this command to start the UI:")
    print("  modal serve ui/app.py")
    print()
    print("Then open the URL shown in the terminal.")
    print("=" * 70)


if __name__ == "__main__":
    setup()
